export const PAYMENT_STEP = {
  DETAILS: "view_merchant_details",
  AMOUNT: "payment_amount",
  METHOD: "payment_method",
  CARD: "card_details",
  CONFIRMATION: "confirm_payment",
  SUCCESS: "payment_success",
  ERROR: "error",
  LOADING: "loading",
};

export const BUTTON_ICONS = {
  PAYSTACK: "paystack",
  APPLE: "apple",
  GOOGLE_PAY: "google_pay",
  CARD: "card",
  ABSA: "absa_bank_kenya",
  KCB: "kenya_commercial_bank",
  NBK: "national_bank_of-kenya",
};

export const PAYMENT_CONSTANTS = {
  FETCH_TRANSACTION_REQUEST: "FETCH_TRANSACTION_REQUEST",
  FETCH_TRANSACTION_SUCCESS: "FETCH_TRANSACTION_SUCCESS",
  FETCH_TRANSACTION_FAIL: "FETCH_TRANSACTION_FAIL",
  INITIALISE_PAYMENT_REQUEST: "INITIALISE_PAYMENT_REQUEST",
  INITIALISE_PAYMENT_SUCCESS: "INITIALISE_PAYMENT_SUCCESS",
  INITIALISE_PAYMENT_FAIL: "INITIALISE_PAYMENT_FAIL",
  VERIFY_TRANSACTION_REQUEST: "VERIFY_TRANSACTION_REQUEST",
  VERIFY_TRANSACTION_SUCCESS: "VERIFY_TRANSACTION_SUCCESS",
  VERIFY_TRANSACTION_FAIL: "VERIFY_TRANSACTION_FAIL",
}
export const CURRENCY_SYMBOL = "₦";
